import type { labelValuePair } from '@/types'

export const categories: labelValuePair[] = [
  { value: "frontend_dev", label: "Frontend Developer" },
  { value: "backend_dev", label: "Backend Developer" },
  { value: "fullstack_dev", label: "Full Stack Developer" },
  { value: "devops_engineer", label: "DevOps Engineer" },
  { value: "ml_engineer", label: "Machine Learning Engineer" },
  { value: "data_engineer", label: "Data Engineer" },
  { value: "3d_designer", label: "3D Designer" },
  { value: "ui_ux_designer", label: "UI/UX Designer" },
  { value: "software_engineer", label: "Software Engineer" },
  { value: "network_engineer", label: "Network Engineer" },
  { value: "security_engineer", label: "Security Engineer" },
  { value: "game_developer", label: "Game Developer" },
  { value: "mobile_app_dev", label: "Mobile App Developer" },
  { value: "cloud_architect", label: "Cloud Architect" },
  { value: "system_admin", label: "System Administrator" },
  { value: "quality_assurance", label: "Quality Assurance Engineer" },
  { value: "product_manager", label: "Product Manager" },
  { value: "hardware_engineer", label: "Hardware Engineer" },
  { value: "blockchain_developer", label: "Blockchain Developer" },
  { value: "embedded_systems_engineer", label: "Embedded Systems Engineer" },
  { value: "web_developer", label: "Web Developer" },
  { value: "database_administrator", label: "Database Administrator" },
  { value: "AI_engineer", label: "Artificial Intelligence Engineer" },
  { value: "AR_VR_developer", label: "AR/VR Developer" },
  { value: "bioinformatics_scientist", label: "Bioinformatics Scientist" },
  { value: "iot_engineer", label: "IoT Engineer" },
  { value: "test_automation_engineer", label: "Test Automation Engineer" },
  { value: "cybersecurity_analyst", label: "Cybersecurity Analyst" },
  { value: "mobile_game_developer", label: "Mobile Game Developer" },
  { value: "cloud_engineer", label: "Cloud Engineer" },
  { value: "data_scientist", label: "Data Scientist" },
  { value: "IT_consultant", label: "IT Consultant" },
];
