import type { labelValuePair } from '@/types'

export const languages: labelValuePair[] = [
  { value: "Python", label: "Python" },
  { value: "Java", label: "Java" },
  { value: "C++", label: "C++" },
  { value: "C#", label: "C#" },
  { value: "Ruby", label: "Ruby" },
  { value: "Swift", label: "Swift" },
  { value: "Go", label: "Go" },
  { value: "Solidity", label: "Solidity" },
  { value: "Dart", label: "Dart" },
  { value: "JavaScript", label: "JavaScript" },
  { value: "Rust", label: "Rust" },
  { value: "Kotlin", label: "Kotlin" },
  { value: "PHP", label: "PHP" },
  { value: "TypeScript", label: "TypeScript" },
  { value: "Perl", label: "Perl" },
  { value: "Scala", label: "Scala" },
  { value: "Haskell", label: "Haskell" },
  { value: "Lua", label: "Lua" },
  { value: "Objective-C", label: "Objective-C" },
  { value: "R", label: "R" },
  { value: "Groovy", label: "Groovy" },
  { value: "Racket", label: "Racket" },
  { value: "Elixir", label: "Elixir" },
  { value: "COBOL", label: "COBOL" },
  { value: "F#", label: "F#" },
  { value: "Ada", label: "Ada" },
  { value: "Rexx", label: "Rexx" },
  { value: "VHDL", label: "VHDL" },
  { value: "Prolog", label: "Prolog" },
  { value: "Erlang", label: "Erlang" },
  { value: "Clojure", label: "Clojure" },
  { value: "Pascal", label: "Pascal" },
];
