import type { labelValuePair } from '@/types'

export const skills: labelValuePair[] = [
  { value: "ml", label: "Machine Learning" },
  { value: "python", label: "Python" },
  { value: "java", label: "Java" },
  { value: "c++", label: "C++" },
  { value: "c#", label: "C#" },
  { value: "ruby", label: "Ruby" },
  { value: "swift", label: "Swift" },
  { value: "go", label: "Go" },
  { value: "react", label: "React" },
  { value: "angular", label: "Angular" },
  { value: "vue.js", label: "Vue.js" },
  { value: "next.js", label: "Next.js" },
  { value: "trpc", label: "tRPC" },
  { value: "graphql", label: "Graphql" },
  { value: "node.js", label: "Node.js" },
  { value: "bun", label: "Bun" },
  { value: "django", label: "Django" },
  { value: "flask", label: "Flask" },
  { value: "ruby on rails", label: "Ruby on Rails" },
  { value: "mysql", label: "MySQL" },
  { value: "supabase", label: "Supabase" },
  { value: "postgresql", label: "PostgreSQL" },
  { value: "mongodb", label: "MongoDB" },
  { value: "firebase", label: "Firebase" },
  { value: "mongodb atlas", label: "MongoDB Atlas" },
  { value: "cassandra", label: "Cassandra" },
  { value: "redis", label: "Redis" },
  { value: "aws aurora", label: "AWS Aurora" },
  { value: "tensor flow", label: "TensorFlow" },
  { value: "pytorch", label: "PyTorch" },
  { value: "keras", label: "Keras" },
  { value: "scikit-learn", label: "Scikit-learn" },
  { value: "opencv", label: "OpenCV" },
  { value: "scipy", label: "SciPy" },
  { value: "pandas", label: "Pandas" },
  { value: "aws", label: "Amazon Web Services (AWS)" },
  { value: "microsoft azure", label: "Microsoft Azure" },
  { value: "google cloud platform", label: "Google Cloud Platform (GCP)" },
  { value: "heroku", label: "Heroku" },
  { value: "digitalocean", label: "DigitalOcean" },
  { value: "git", label: "Git" },
  { value: "github", label: "GitHub" },
  { value: "gitlab", label: "GitLab" },
  { value: "jenkins", label: "Jenkins" },
  { value: "docker", label: "Docker" },
  { value: "kubernetes", label: "Kubernetes" },
  { value: "ansible", label: "Ansible" },
  { value: "puppet", label: "Puppet" },
  { value: "jest", label: "Jest" },
  { value: "pytest", label: "Pytest" },
  { value: "unittest", label: "Unittest" },
  { value: "selenium", label: "Selenium" },
  { value: "cypress", label: "Cypress" },
  { value: "mocha", label: "Mocha" },
  { value: "chai", label: "Chai" },
  { value: "owasp", label: "OWASP" },
  { value: "ssl/tls", label: "SSL/TLS" },
  { value: "https", label: "HTTPS" },
  { value: "ssh", label: "SSH" },
  { value: "pgp", label: "PGP" },
  { value: "gpg", label: "GPG" },
  { value: "jwt", label: "JWT" },
  { value: "csrf", label: "CSRF" },
  { value: "react native", label: "React Native" },
  { value: "flutter", label: "Flutter" },
  { value: "xamarin", label: "Xamarin" },
  { value: "ionic", label: "Ionic" },
  { value: "phonegap", label: "PhoneGap" },
  { value: "blockchain", label: "Blockchain" },
  { value: "ethereum", label: "Ethereum" },
  { value: "solidity", label: "Solidity" },
  { value: "web3.js", label: "Web3.js" },
  { value: "truffle", label: "Truffle" },
  { value: "ganache", label: "Ganache" },
  { value: "metamask", label: "MetaMask" },
  { value: "iot", label: "IoT" },
  { value: "raspberry pi", label: "Raspberry Pi" },
  { value: "arduino", label: "Arduino" },
  { value: "esp32", label: "ESP32" },
  { value: "esp8266", label: "ESP8266" },
  { value: "nodemcu", label: "NodeMCU" },
  { value: "particle photon", label: "Particle Photon" },
  { value: "particle electron", label: "Particle Electron" },
  { value: "artificial intelligence", label: "Artificial Intelligence" },
  { value: "natural language processing", label: "Natural Language Processing" },
  { value: "nlp", label: "NLP" },
  { value: "word2vec", label: "Word2Vec" },
  { value: "gensim", label: "Gensim" },
  { value: "tensorflow nlp", label: "TensorFlow NLP" },
  { value: "stanford corenlp", label: "Stanford CoreNLP" },
  { value: "augmented reality", label: "Augmented Reality" },
  { value: "virtual reality", label: "Virtual Reality" },
  { value: "arkit", label: "ARKit" },
  { value: "arcore", label: "ARCore" },
  { value: "vuforia", label: "Vuforia" },
  { value: "unity", label: "Unity" },
  { value: "unreal engine", label: "Unreal Engine" },
  { value: "music theory", label: "Music Theory" },
  { value: "pitch detection", label: "Pitch Detection" },
  { value: "beat detection", label: "Beat Detection" },
  { value: "audio signal processing", label: "Audio Signal Processing" },
  { value: "midi", label: "MIDI" },
  { value: "video production", label: "Video Production" },
  { value: "animation", label: "Animation" },
  { value: "adobe premiere pro", label: "Adobe Premiere Pro" },
  { value: "final cut pro", label: "Final Cut Pro" },
  { value: "davinci resolve", label: "Davinci Resolve" },
  { value: "blender", label: "Blender" },
  { value: "after effects", label: "After Effects" },
  { value: "animate cc", label: "Animate CC" },
  { value: "graphic design", label: "Graphic Design" },
  { value: "visual arts", label: "Visual Arts" },
  { value: "adobe photoshop", label: "Adobe Photoshop" },
  { value: "adobe illustrator", label: "Adobe Illustrator" },
  { value: "adobe indesign", label: "Adobe InDesign" },
  { value: "sketch", label: "Sketch" },
  { value: "figma", label: "Figma" },
  { value: "gravit designer", label: "Gravit Designer" },
  { value: "latex", label: "LaTeX" },
  { value: "agile", label: "Agile" },
  { value: "scrum", label: "Scrum" },
  { value: "trello", label: "Trello" },
  { value: "discord bot", label: "Discord Bot Development" },
]