import type { labelValuePair } from '@/types'

export const tags: labelValuePair[] = [
  { value: "webdev", label: "Web Development" },
  { value: "fullstack", label: "Full Stack Development" },
  { value: "web3", label: "Web3" },
  { value: "gamedev", label: "Game Development" },
  { value: "uiux", label: "UI/UX Design" },
  { value: "ml", label: "Machine Learning" },
  { value: "dl", label: "Deep Learning" },
  { value: "ai", label: "Artificial Intelligence" },
  { value: "devops", label: "DevOps" },
  { value: "cloud", label: "Cloud Computing" },
  { value: "blockchain", label: "Blockchain" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "datascience", label: "Data Science" },
  { value: "bigdata", label: "Big Data" },
  { value: "iot", label: "Internet of Things (IoT)" },
  { value: "mobiledev", label: "Mobile Development" },
  { value: "frontend", label: "Frontend Development" },
  { value: "backend", label: "Backend Development" },
  { value: "ios", label: "iOS Development" },
  { value: "android", label: "Android Development" },
  { value: "database", label: "Database Management" },
];
